src/bunchup/urls.py
from django.urls import path
from .views import HomeView, HubView, HubCreateView, HubUpdateView, HubDeleteView, ActivityView, ActivityCreateView, \
    ActivityJoinView, HubJoinView, HubLeaveView, ActivityLeaveView, ActivityUpdateView, RoomDeleteView, RoomUpdateView, \
    RoomCreateView, get_hub_messages

urlpatterns = [
    path('', HomeView.as_view(), name='bunchup-home'),
    path('hub/<int:pk>/', HubView.as_view(), name='bunchup-hub'),
    path('hub/<int:pk>/edit/', HubUpdateView.as_view(), name='bunchup-hub-update'),
    path('hub/<int:pk>/delete/', HubDeleteView.as_view(), name='bunchup-hub-delete'),
    path('hub/<int:pk>/join', HubJoinView.as_view(), name='bunchup-hub-join'),
    path('hub/<int:pk>/leave', HubLeaveView.as_view(), name='bunchup-hub-leave'),
    path('activity/<int:pk>/', ActivityView.as_view(), name='bunchup-activity'),
    path('activity/<int:pk>/delete/', ActivityView.as_view(), name='bunchup-activity-delete'),
    path('activity/<int:pk>/edit/', ActivityUpdateView.as_view(), name='bunchup-activity-update'),
    path('activity/<int:pk>/join/', ActivityJoinView.as_view(), name='bunchup-activity-join'),
    path('activity/<int:pk>/leave/', ActivityLeaveView.as_view(), name='bunchup-activity-leave'),
    path('create/hub/', HubCreateView.as_view(), name='bunchup-hub-create'),
    path('hub/<int:pk>/create/activity/', ActivityCreateView.as_view(), name='bunchup-activity-create'),
    path('hub/<int:pk>/create/room', RoomCreateView.as_view(), name='bunchup-room-create'),
    path('room/<int:pk>/edit/', RoomUpdateView.as_view(), name='bunchup-room-update'),
    path('room/<int:pk>/delete/', RoomDeleteView.as_view(), name='bunchup-room-delete'),

    path('api/room/<int:room_pk>/messages/', get_hub_messages, name="api-get-hub-messages")
]

src/users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', user_views.logout_view, name='logout'),
    # path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-change/', user_views.password_change, name='password-change'),
    path('profile/', user_views.profile, name='profile')
]

src/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bunchup.urls')),
    path('', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/bunchup/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from tagging.registry import register
from tagging.fields import TagField

from PIL import Image

def one_day_hence():
    return timezone.now() + timezone.timedelta(days=1)
    
    
class Tag(models.Model):
    title = models.CharField(max_length=32)

    def __str__(self):
        return self.title


class Hub(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=1024)
    locked = models.BooleanField(default=False)
    # tags = models.ManyToManyField(Tag, blank=True)
    tags = TagField()
    users = models.ManyToManyField(User, through='Membership', blank=True)
    image = models.ImageField(default='default-hub.png', upload_to='hub_pics')

    def save(self, **kwargs):
        super().save()
        img = Image.open(self.image.path)

        target_width = 346
        target_height = 216

        if img.height > target_height or img.width > target_width:
            size = (target_width, target_height)
            img.thumbnail(size, Image.ANTIALIAS)
            img.save(self.image.path)

    def __str__(self):
        return self.name


class Activity(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=1024)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE, null=True)
    room = models.OneToOneField('Room', on_delete=models.CASCADE, null=True, blank=True)
    tags = TagField()
    start_date = models.DateTimeField(default=timezone.now)
    finish_date = models.DateTimeField(default=one_day_hence())
    users = models.ManyToManyField(User, blank=True)
    image = models.ImageField(default='default-activity.png', upload_to='activity_pics')

    def save(self, **kwargs):
        super().save()
        img = Image.open(self.image.path)

        target_width = 346
        target_height = 216

        if img.height > target_height or img.width > target_width:
            size = (target_width, target_height)
            img.thumbnail(size, Image.ANTIALIAS)
            img.save(self.image.path)


    def __str__(self):
        return self.name


class Room(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=1024)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE, blank=True, null=True)
    activity_room = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Message(models.Model):
    text = models.CharField(max_length=1024)
    # on_delete => Set to null user. Message remains after account deletion.
    owner = models.ForeignKey(User, on_delete=models.SET(0))
    date_time = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(Room, related_name="messages", on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hub = models.ForeignKey(Hub, on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)

    def __str__(self):
        return str('%s %s %s %s %s %s' % ("Hub:", self.hub, "| Member:", self.user, "| Admin:", self.is_admin))

src/bunchup/forms.py
# forms.py
from django import forms
from .models import Hub

# from tagging import fields as tagfields

class ImageUploadForm(forms.ModelForm):
    # tags = tagfields.TagField()

    class Meta:
        model = Hub
        fields = ['name', 'description', 'locked', 'tags', 'image']

src/bunchup/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View

from tagging.models import Tag, TaggedItem
from titlecase import titlecase

from .models import Hub, Activity, Membership, Room
from .forms import ImageUploadForm

class HomeView(ListView):
    model = Hub
    template_name = 'bunchup/index.html'
    context_object_name = 'hubs'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["highlights"] = {}

        featured = Hub.objects.all()
        context["highlights"]["Featured Hubs"] = featured

        activities = Activity.objects.all()
        context["highlights"]["Activities"] = activities

        for tag in Tag.objects.all():
            titled_tag_name = titlecase(tag.name)

            try:
                tag_hubs = TaggedItem.objects.get_by_model(Hub, tag)

                if len(tag_hubs) > 0:
                    context["highlights"][f"{titled_tag_name} Hubs"] = tag_hubs
            except Tag.DoesNotExist:
                pass

            try:
                tag_activities = TaggedItem.objects.get_by_model(Activity, tag)

                if len(tag_activities) > 0:
                    context["highlights"][f"{titled_tag_name} Activities"] = tag_activities
            except Tag.DoesNotExist:
                pass

        return context
    

class HubView(DetailView):
    model = Hub
    
    def get_context_data(self, **kwargs):
        context = super(HubView, self).get_context_data(**kwargs)
        hub = self.get_object()
        members = hub.membership_set.filter()
        admins = []
        users = []
        context['total_users'] = len(hub.users.all())
        for member in members:
            users.append(member.user)
            if member.is_admin:
                admins.append(member.user)
        context['activities'] = Activity.objects.filter(hub=self.kwargs.get('pk'))
        context['next_activity'] = context['activities'][0] if context['activities'] else None
        context['admins'] = admins
        return context

class HubCreateView(LoginRequiredMixin, CreateView):
    model = Hub
    form_class = ImageUploadForm

    def form_valid(self, form):
        self.object = form.save()
        Membership.objects.create(
            user=self.request.user,
            hub=self.object,
            is_admin=True
        )
        general_room = Room(name="General",
                            description="A general room to discuss anything.",
                            hub=self.object,
                            activity_room=False)
        general_room.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-hub", kwargs={"pk": str(self.object.pk)}))


class HubUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Hub
    form_class = ImageUploadForm
    context_object_name = 'hubs'
    template_name = 'bunchup/hub_update.html'

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-hub", kwargs={"pk": str(self.object.pk)}))

    def test_func(self):
        hub = self.get_object()
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


class HubDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Hub
    success_url = '/'
        
    def test_func(self):
        hub = self.get_object()
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


class ActivityView(DetailView):
    model = Activity
    template_name = 'bunchup/activity.html'
    context_object_name = 'activity'

    def get_context_data(self, **kwargs):
        context = super(ActivityView, self).get_context_data(**kwargs)
        activity = self.get_object()
        total_users = len(activity.users.all())

        context["chat_messages"] = activity.room.messages.all()

        return context


class ActivityCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Activity
    context_object_name = 'activities'
    fields = ['name', 'description', 'tags', 'start_date', 'finish_date']

    def form_valid(self, form):
        self.object = form.save()
        pk = self.kwargs['pk']
        self.object.hub = Hub.objects.get(pk=pk)
        self.object.users.add(self.request.user)
        room = Room(name=self.object.name,
                    description=self.object.description,
                    hub=self.object.hub,
                    activity_room=True
                    )
        room.save()
        self.object.room = room
        self.object.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-activity", kwargs={"pk": str(self.object.pk)}))

    def test_func(self):
        hub = Hub.objects.get(pk=self.kwargs['pk'])
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


class ActivityDeleteView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Activity
    success_url = "/"

    def test_func(self):
        hub = self.object.hub
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


class ActivityUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Activity
    context_object_name = 'activities'
    template_name = 'bunchup/activity_update.html'
    fields = ['name', 'description', 'tags', 'start_date', 'finish_date', 'image']

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-activity", kwargs={"pk": str(self.object.pk)}))

    def test_func(self):
        hub = self.get_object().hub
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


class ActivityJoinView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        activity = Activity.objects.get(pk=kwargs['pk'])
        activity.users.add(self.request.user)
        activity.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-activity", kwargs={"pk": str(activity.pk)}))


class HubJoinView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        hub = Hub.objects.get(pk=kwargs['pk'])
        hub.users.add(self.request.user)
        hub.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-hub", kwargs={"pk": str(hub.pk)}))


class HubLeaveView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        hub = Hub.objects.get(pk=kwargs['pk'])
        hub.users.remove(self.request.user)
        hub.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-hub", kwargs={"pk": str(hub.pk)}))


class ActivityLeaveView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        activity = Activity.objects.get(pk=kwargs['pk'])
        activity.users.remove(self.request.user)
        activity.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-activity", kwargs={"pk": str(activity.pk)}))


class RoomCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Room
    context_object_name = 'rooms'
    fields = ['name', 'description']

    def form_valid(self, form):
        self.object = form.save()
        pk = self.kwargs['pk']
        self.object.hub = Hub.objects.get(pk=pk)
        self.object.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-room", kwargs={"pk": str(self.object.pk)}))

    def test_func(self):
        hub = Hub.objects.get(pk=self.kwargs['pk'])
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


class RoomUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Room
    context_object_name = 'rooms'
    fields = ['name', 'description']

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(reverse_lazy("bunchup-room", kwargs={"pk": str(self.object.pk)}))

    def test_func(self):
        hub = self.get_object().hub
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


class RoomDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Room
    success_url = '/'

    def test_func(self):
        hub = self.get_object().hub
        if hub.membership_set.filter(user=self.request.user).exists():
            return hub.membership_set.get(user=self.request.user).is_admin
        else:
            return False


def get_hub_messages(request, room_pk):
    room = Room.objects.get(id=room_pk)
    room_messages = room.messages.all()

    data = []
    for message in room_messages:
        data.append({
            "text": message.text,
            "owner": message.owner.username,
            "picture": message.owner.profile.image.url
        })

    return JsonResponse(data, safe=False)

src/bunchup/templates/bunchup/activity_form.html
{% extends "bunchup/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section cute-container mx-auto">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Activity</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

src/bunchup/templates/bunchup/activity_update.html
{% extends "bunchup/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
		<div class="content-section cute-container mx-auto">
			<form enctype="multipart/form-data" method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Update Activity</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Submit</button>
				</div>
			</form>
		</div>
{% endblock content %}

src/bunchup/templates/bunchup/hub_confirm_delete.html
{% extends "bunchup/base.html" %}

{% block content %}
		<div class="content-section cute-container mx-auto">
			<form method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Delete Hub</legend>
					<h3>{{ hub.name }}</h3>
				</fieldset>
				<div class="form-group">
					<p>Are you sure you want to delete this hub?</p>
					<button class="btn btn-danger" type="submit">Delete</button>
				</div>
			</form>
		</div>
{% endblock content %}

src/bunchup/templates/bunchup/hub_detail.html
{% extends "bunchup/base.html" %}
{% load static %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<div class="media content-section mx-auto">
				
				<div class="media-body">
					<h2><img class="rounded-circle hub-icon" src="{{ hub.image.url }}"> {{ hub.name }}</h2>
					<p class="mb-1">Hosted by{% for admin in admins %} {{ admin.username }} <img class="rounded-circle hub-icon" src="{{ admin.profile.image.url }}">{% endfor %}</p>
                    <p>Users: {{ total_users }}</p>
					<hr>
					<p>{{ hub.description }}</p>
					<div>
						{% if user in admins %}
							<a class="btn btn-info btn-sm mt-1 mb-1" href="{% url 'bunchup-activity-create' hub.id %}">New Activity</a>
						{% endif %}
						{% if user in users %}
							<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'bunchup-hub-join' hub.id %}">Join Hub</a>
						{% else %}
							<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'bunchup-hub-leave' hub.id %}">Leave Hub</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		{% if next_activity %}
		<div class="col-md-12">
			<div class="media-body cute-container content-section mx-auto">
				<h2>Next Activity</h2>
				<a class="d-block-inline col-md-4 no-text-dec mb-4" href="{% url 'bunchup-activity' next_activity.id %}">
					<div class="card box-shadow">
						<img class="card-img-top" src="{{ next_activity.image.url }}" alt="Card image cap">
						<div class="card-body px-3 py-2">
							<h4>{{ next_activity.name }}</h4>
							<small class="card-text">{{ next_activity.description }}</small>
						</div>
					</div>
				</a>
			</div>
		</div>
		{% endif %}
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="media content-section mx-auto">
				<div class="media-body">

				<h2>Channels</h2>
                    {% for room in hub.room_set.all %}
                        {% if not room.activity_room %}
                            <div id="room-{{ room.id }}" class="p-1 rounded bg-light">
                            {{ room }}
                            </div>

                            <script>
                                setTimeout(() => {
                                    $(`#room-{{ room.id }}`).click(() => {

                                        changeRoomSocket({{ room.id }})
                                        loadAllMessages({{ room.id }})
                                    });
                                }, 0);
                            </script>
                        {% endif %}
                    {% endfor %}
				</div>
			</div>
		</div>
		<div class="col-md-9">
			<div class="media content-section mx-auto">
				<div class="media-body">
                <h2>Chat Room</h2>

                <div class="form-control" id="chat-log"></div>

                <div class="row mt-2 no-gutters">
                    <div id="chat-message-entry" class="col">
                        <input class="form-control bg-light" id="chat-message-input" type="text" placeholder="Type a message..."><br>
                    </div>
                    <div id="chat-message-submit" class="col bg-primary rounded pl-1 pt-1 ml-2">
                        <img src="{% static 'bunchup/img/send.svg' %}"></img>
                    </div>
                </div>
			</div>
		</div>
	</div>
	{% if next_activity %}
	<div class="content-section mx-auto">
		<h2>Upcoming Activities</h2>
		<div class="row">
			{% for activity in activities %}
				<a class="d-block-inline col-md-4 no-text-dec mb-4" href="{% url 'bunchup-activity' activity.id %}">
					<div class="card box-shadow">
						<img class="card-img-top" src="{{ activity.image.url }}" alt="Card image cap">
						<div class="card-body px-3 py-2">
							<h4>{{ activity.name }}</h4>
							<small class="card-text">{{ activity.description }}</small>
						</div>
					</div>
				</a>
			{% endfor %}
		</div>
	</div>
	{% endif %}
		<div class="media content-section cute-container mx-auto">
			<div class="media-body">
			{% if user in admins %}
				<h2 class="article-title">Admin Controls</h2>
				<div>
					<a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'bunchup-hub-update' hub.id %}">Update</a>
					<a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'bunchup-hub-delete' hub.id %}">Delete</a>
				</div>
				{% endif %}
			</div>
		</div>

    {{ hub.id|json_script:"hub-id" }}
    <script>
        let chatLog = document.querySelector("#chat-log");
        var currentRoomId = {{ hub.room_set.all.0.id }};

        function scrollChatToBottom() {
            chatLog.scrollTop = chatLog.scrollHeight;
        }

        function addMessage(message) {
            let rootRow = document.createElement("div");

            let nameRow = document.createElement("div");
            nameRow.className = "row ml-1";

            let nameRowSpace = document.createElement("div");
            nameRowSpace.className = "col chat-profile-icon";

            nameRow.appendChild(nameRowSpace);

            let name = document.createElement("div");
            name.className="col"
            name.textContent = message.owner;
            
            nameRow.appendChild(name);

            //

            let chatMessage = document.createElement("div");
            chatMessage.className = "d-inline-block bg-light rounded chat-message py-2 px-3 ml-2";
            chatMessage.textContent = message.text;

            let messageContainer = document.createElement("div");
            messageContainer.className = "col";

            messageContainer.appendChild(chatMessage);

            let chatProfileImage = document.createElement("img");
            chatProfileImage.className = "d-inline rounded-circle chat-profile-icon";

            console.log(message.picture);
            chatProfileImage.src = message.picture;

            let imageContainer = document.createElement("div");
            imageContainer.className = "col chat-profile-icon";

            imageContainer.appendChild(chatProfileImage);

            let row = document.createElement("div");
            row.className = "row mb-2";

            row.appendChild(imageContainer);
            row.appendChild(messageContainer);

            //

            rootRow.appendChild(nameRow)
            rootRow.appendChild(row);

            chatLog.appendChild(rootRow);

            scrollChatToBottom();
        }

        const hubId = JSON.parse(document.getElementById("hub-id").textContent);

        let chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/room/'
            + currentRoomId
            + '/'
        );

        function changeRoomSocket(roomId) {
            // chatSocket.close();
            chatSocket = new WebSocket(
                'ws://'
                + window.location.host
                + '/ws/room/'
                + roomId
                + '/'
            )

            document.querySelector('#chat-message-submit').onclick = function(e) {
                const messageInputDom = document.querySelector('#chat-message-input');
                const message = messageInputDom.value;
                chatSocket.send(JSON.stringify({
                    'message': message,
                    'room': currentRoomId
                }));
                messageInputDom.value = '';
            };
        }

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            addMessage(data);
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'room': currentRoomId
            }));
            messageInputDom.value = '';
        };

        function loadAllMessages(roomId) {
            $("#chat-log").html("");
            currentRoomId = roomId;
            $.ajax({
                url: `/api/room/${roomId}/messages/`,
                success: (data) => {
                    console.log(roomId);
                    for (var message of data) {
                        addMessage(message);
                    }
                },
                error: (error) => {
                    console.error("Couldn't load hub chat messages.");
                    console.error(error);
                }
            });
        }

        // Let jquery load
        setTimeout(() => {
            loadAllMessages(currentRoomId);
        }, 0);
    </script>
{% endblock content %}

src/bunchup/templates/bunchup/hub_form.html
{% extends "bunchup/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
		<div class="content-section cute-container mx-auto">
			<form enctype="multipart/form-data" method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Create Hub</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Submit</button>
				</div>
			</form>
		</div>
{% endblock content %}

src/bunchup/templates/bunchup/hub_update.html
{% extends "bunchup/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
		<div class="content-section cute-container mx-auto">
			<form enctype="multipart/form-data" method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Update Hub</legend>
					{{ form|crispy }}
				</fieldset>
				<div class="form-group">
					<button class="btn btn-outline-info" type="submit">Submit</button>
				</div>
			</form>
		</div>
{% endblock content %}

src/bunchup/templates/bunchup/index.html
{% extends "bunchup/base.html" %}

{% block content %}
    <section class="jumbotron text-center">
      <div class="container">
        {% if user.is_authenticated %}
            <h1 class="jumbotron-heading">Hello! 👋</h1>
            <h3 class="lead">Browse some of the activities going on today.</h3>
        {% else %}
            <h1 class="jumbotron-heading">Welcome!</h1>
            <h3 class="lead">Bunchup makes it super easy to find people to play with.</h3>
            <p>
                <a href="{% url 'register' %}" class="btn btn-bunchup my-2">Join Bunchup</a>
            </p>
        {% endif %}
      </div>
    </section>

    {% for highlight_name, highlights in highlights.items %}
	<h1 class="mb-4">{{ highlight_name }}</h1>
    <div class="row">
        {% for highlight in highlights %}

        {% if highlight.hub %}
        <a class="d-block-inline col-md-4 no-text-dec mb-4" href="{% url 'bunchup-activity' highlight.id %}">
        {% else %}
        <a class="d-block-inline col-md-4 no-text-dec mb-4" href="{% url 'bunchup-hub' highlight.id %}">
        {% endif %}
            <div class="card box-shadow">
                <img class="card-img-top" src="{{ highlight.image.url }}" alt="Card image cap">
                <div class="card-body px-3 py-2">
                    <h4>{{ highlight.name }}</h4>
                    <small class="card-text">{{ highlight.description }}</small>
                </div>
            </div>
        </a>

        {% empty %}

        <p class="mb-4 ml-3">
            No hubs or activities are active right now.
        </p>

        {% endfor %}
	</div>
    {% endfor %}
    
{% endblock content %}

src/bunchup/templates/bunchup/room_confirm_delete.html
{% extends "bunchup/base.html" %}

{% block content %}
		<div class="content-section cute-container mx-auto">
			<form method="POST">
				{% csrf_token %}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Delete Room</legend>
					<h3>{{ hub.name }}</h3>
				</fieldset>
				<div class="form-group">
					<p>Are you sure you want to delete this room?</p>
					<button class="btn btn-danger" type="submit">Delete</button>
				</div>
			</form>
		</div>
{% endblock content %}